---
version: "3.9"
services:

  migration:
    image: aorticweb/msg-app-migration
    build:
      context: .
      dockerfile: containers/migration/Dockerfile
    environment:
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    volumes:
      - ./db/migrations:/db/migrations:rw
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    image: postgres:13.3-alpine
    volumes:
      - ./db/conf/postgresql.conf:/etc/postgresql.conf
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      PGDATA: /data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432  
    networks:
      - default

networks:
  default: